// <auto-generated />
using System;
using DataAccessLayer.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221123184622_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "35ca7aad-d2b3-49f4-ad0c-1fdbc2ed7ed8",
                            ConcurrencyStamp = "1b39fd11-6793-457b-9cee-f095f0f070ad",
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 245, DateTimeKind.Local).AddTicks(4893),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 245, DateTimeKind.Local).AddTicks(4906),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 245, DateTimeKind.Local).AddTicks(4902),
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "ab2e09bf-cc27-43b5-bed9-1cc81c957abb",
                            ConcurrencyStamp = "b32fb2cf-1c1a-4668-b492-c68a03deab52",
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 245, DateTimeKind.Local).AddTicks(4916),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 245, DateTimeKind.Local).AddTicks(4918),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 245, DateTimeKind.Local).AddTicks(4917),
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "4764c00a-422f-4fe1-bfd5-cc43895c14f3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2cdd2d50-af98-4ea2-9e8c-6d7912546d2b",
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 246, DateTimeKind.Local).AddTicks(9626),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 246, DateTimeKind.Local).AddTicks(9633),
                            Email = "user1@user.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(2022, 11, 23, 18, 46, 22, 246, DateTimeKind.Unspecified).AddTicks(9619), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 246, DateTimeKind.Local).AddTicks(9631),
                            NormalizedEmail = "USER1@USER.COM",
                            NormalizedUserName = "USER1@USER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPKxEnAgNpvt/UxyNj415jy4auZgr27TTEKKFSsi+doXccA4KTIlAyFZlWc0rCul+w==",
                            PhoneNumber = "+905554443322",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eb596ef2-9ef0-42f9-bdd2-2326b56edc40",
                            TwoFactorEnabled = false,
                            UserName = "user1@user.com"
                        },
                        new
                        {
                            Id = "044d5ec8-3699-471c-be73-8a9b29a8a3c5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26b0556f-d5ef-4b65-9521-9378b7c68d78",
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 254, DateTimeKind.Local).AddTicks(7531),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 254, DateTimeKind.Local).AddTicks(7534),
                            Email = "user2@user.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(2022, 11, 23, 18, 46, 22, 254, DateTimeKind.Unspecified).AddTicks(7527), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 254, DateTimeKind.Local).AddTicks(7533),
                            NormalizedEmail = "USER1@USER.COM",
                            NormalizedUserName = "USER2@USER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEN9Poi2qaoLIMT1OODpPj25YrjQgxqD5hUFRE6DzVLKNQgYFUKcGoMIUcbnQjtnNfQ==",
                            PhoneNumber = "+905554443322",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c015ff47-aee6-4b64-9fc8-ed9bc41e09c5",
                            TwoFactorEnabled = false,
                            UserName = "user2@user.com"
                        },
                        new
                        {
                            Id = "e26796d3-0f85-48fe-a864-4f523107c3bb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "075ae475-dca8-4196-9573-1c2ea16618c0",
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 262, DateTimeKind.Local).AddTicks(4132),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 262, DateTimeKind.Local).AddTicks(4137),
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(2022, 11, 23, 18, 46, 22, 262, DateTimeKind.Unspecified).AddTicks(4127), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 262, DateTimeKind.Local).AddTicks(4136),
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHwEfmCcI9plDlzTCCnGf5DUK6pZWA/a/WoWwi/7kbrspXMd5muadqn0cGpTmS7mAQ==",
                            PhoneNumber = "+905554443322",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f04fe7ab-46d7-4fe8-85b2-cde90762da0e",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = "b4a23211-6cba-4cd1-9e27-0b50aa6294d9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "824f10db-1812-40ee-977a-4060b12c94ab",
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 270, DateTimeKind.Local).AddTicks(1055),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 270, DateTimeKind.Local).AddTicks(1058),
                            Email = "manager@manager.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = true,
                            LockoutEnd = new DateTimeOffset(new DateTime(2022, 11, 23, 18, 46, 22, 270, DateTimeKind.Unspecified).AddTicks(1052), new TimeSpan(0, 0, 0, 0, 0)),
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 270, DateTimeKind.Local).AddTicks(1057),
                            NormalizedEmail = "MANAGER@MANAGER.COM",
                            NormalizedUserName = "MANAGER@MANAGER.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECza8b1ObxeLKrLHdFFNfecXC5PBMrzBGjNDtKROFrlmxmdonqGrPApdmZgHcLx1HQ==",
                            PhoneNumber = "+905554443322",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27ef6515-18f7-461b-bdfa-a15a12b2fccc",
                            TwoFactorEnabled = false,
                            UserName = "manager@manager.com"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Appointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Confirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSalonRatedByTheUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.HasIndex("SalonId", "ServiceId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(2978),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(2994),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            ImageUrl = "../images/Categories/ManCategory.jfif",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(2988),
                            Name = "Erkek"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(2996),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(2998),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            ImageUrl = "../images/Categories/WomanCategory.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(2996),
                            Name = "Kadın"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(3773),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(3779),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(3777),
                            Name = "Ankara"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(3782),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(3785),
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(3783),
                            Name = "İstanbul"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Salon", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RatersCount")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Salons");

                    b.HasData(
                        new
                        {
                            Id = "salon1",
                            Address = "Zeytinburnu",
                            CategoryId = 1,
                            CityId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4136),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4143),
                            ImageUrl = "../images/Salons/ManSalon.jfif",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4141),
                            Name = "Erkek Kuaför 1",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon2",
                            Address = "Zeytinburnu",
                            CategoryId = 1,
                            CityId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4157),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4159),
                            ImageUrl = "../images/Salons/ManSalon.jfif",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4158),
                            Name = "Erkek Kuaför 2",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon3",
                            Address = "Zeytinburnu",
                            CategoryId = 1,
                            CityId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4163),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4165),
                            ImageUrl = "../images/Salons/ManSalon.jfif",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4164),
                            Name = "Erkek Kuaför 3",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon4",
                            Address = "Zeytinburnu",
                            CategoryId = 1,
                            CityId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4168),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4170),
                            ImageUrl = "../images/Salons/ManSalon.jfif",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4169),
                            Name = "Erkek Kuaför 4",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon5",
                            Address = "Zeytinburnu",
                            CategoryId = 1,
                            CityId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4173),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4175),
                            ImageUrl = "../images/Salons/ManSalon.jfif",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4174),
                            Name = "Erkek Kuaför 5",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon6",
                            Address = "Keçiören",
                            CategoryId = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4177),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4179),
                            ImageUrl = "../images/Salons/WomanSalon.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4178),
                            Name = "Kadın Kuaför 1",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon7",
                            Address = "Keçiören",
                            CategoryId = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4182),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4184),
                            ImageUrl = "../images/Salons/WomanSalon.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4183),
                            Name = "Kadın Kuaför 2",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon8",
                            Address = "Keçiören",
                            CategoryId = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4186),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4188),
                            ImageUrl = "../images/Salons/WomanSalon.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4187),
                            Name = "Kadın Kuaför 3",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon9",
                            Address = "Keçiören",
                            CategoryId = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4191),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4193),
                            ImageUrl = "../images/Salons/WomanSalon.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4192),
                            Name = "Kadın Kuaför 4",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon10",
                            Address = "Keçiören",
                            CategoryId = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4196),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4198),
                            ImageUrl = "../images/Salons/WomanSalon.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4197),
                            Name = "Kadın Kuaför 5",
                            RatersCount = 0,
                            Rating = 0.0
                        },
                        new
                        {
                            Id = "salon11",
                            Address = "Keçiören",
                            CategoryId = 2,
                            CityId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4200),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4202),
                            ImageUrl = "../images/Salons/WomanSalon.jpg",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(4201),
                            Name = "Kadın Kuaför 6",
                            RatersCount = 0,
                            Rating = 0.0
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SalonService", b =>
                {
                    b.Property<string>("SalonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("SalonId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("SalonServices");

                    b.HasData(
                        new
                        {
                            SalonId = "salon1",
                            ServiceId = 1,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9679),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9686),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9684)
                        },
                        new
                        {
                            SalonId = "salon1",
                            ServiceId = 2,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9690),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9692),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9691)
                        },
                        new
                        {
                            SalonId = "salon2",
                            ServiceId = 1,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9694),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9695),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9695)
                        },
                        new
                        {
                            SalonId = "salon2",
                            ServiceId = 2,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9697),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9699),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9698)
                        },
                        new
                        {
                            SalonId = "salon3",
                            ServiceId = 1,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9701),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9702),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9701)
                        },
                        new
                        {
                            SalonId = "salon3",
                            ServiceId = 2,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9704),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9706),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9705)
                        },
                        new
                        {
                            SalonId = "salon4",
                            ServiceId = 1,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9709),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9711),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9709)
                        },
                        new
                        {
                            SalonId = "salon4",
                            ServiceId = 2,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9718),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9720),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9719)
                        },
                        new
                        {
                            SalonId = "salon5",
                            ServiceId = 1,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9721),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9723),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9722)
                        },
                        new
                        {
                            SalonId = "salon5",
                            ServiceId = 2,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9725),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9726),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9725)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 3,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9728),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9730),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9729)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 4,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9732),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9734),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9733)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 5,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9735),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9737),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9736)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 6,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9739),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9741),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9740)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 7,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9742),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9744),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9743)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 8,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9747),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9749),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9747)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 9,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9751),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9753),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9752)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 10,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9755),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9756),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9755)
                        },
                        new
                        {
                            SalonId = "salon6",
                            ServiceId = 11,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9758),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9760),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9759)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 3,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9761),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9763),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9762)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 4,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9765),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9767),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9766)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 5,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9770),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9772),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9771)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 6,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9774),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9776),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9775)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 7,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9779),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9781),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9780)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 8,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9783),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9785),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9784)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 9,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9787),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9789),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9788)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 10,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9790),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9792),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9791)
                        },
                        new
                        {
                            SalonId = "salon7",
                            ServiceId = 11,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9794),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9796),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9795)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 3,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9855),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9858),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9856)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 4,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9860),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9862),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9861)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 5,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9864),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9866),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9865)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 6,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9868),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9869),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9868)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 7,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9873),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9874),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9873)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 8,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9876),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9878),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9877)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 9,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9880),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9882),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9881)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 10,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9884),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9886),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9885)
                        },
                        new
                        {
                            SalonId = "salon8",
                            ServiceId = 11,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9888),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9889),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9888)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 3,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9891),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9893),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9892)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 4,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9896),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9898),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9897)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 5,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9899),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9902),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9900)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 6,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9904),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9905),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9904)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 7,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9907),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9909),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9908)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 8,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9911),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9913),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9912)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 9,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9915),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9917),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9915)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 10,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9919),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9921),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9920)
                        },
                        new
                        {
                            SalonId = "salon9",
                            ServiceId = 11,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9922),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9924),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9923)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 3,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9926),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9928),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9927)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 4,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9929),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9931),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9930)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 5,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9934),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9936),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9934)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 6,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9937),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9939),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9938)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 7,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9941),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9943),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9942)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 8,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9945),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9947),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9946)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 9,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9949),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9951),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9950)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 10,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9953),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9955),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9954)
                        },
                        new
                        {
                            SalonId = "salon10",
                            ServiceId = 11,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9957),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9959),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9958)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 3,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9961),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9963),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9962)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 4,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9966),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9968),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9967)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 5,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9970),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9972),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9971)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 6,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9974),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9976),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9975)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 7,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9978),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9979),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9978)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 8,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9981),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9983),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9982)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 9,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9985),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9987),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9986)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 10,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9989),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9991),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9990)
                        },
                        new
                        {
                            SalonId = "salon11",
                            ServiceId = 11,
                            Available = true,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9992),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9994),
                            Id = 0,
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 280, DateTimeKind.Local).AddTicks(9993)
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(604),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(610),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(608),
                            Name = "Saç Traşı"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(614),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(616),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(615),
                            Name = "Sakal Traşı"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(619),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(620),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(619),
                            Name = "Fön"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(625),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(627),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(626),
                            Name = "Mini Kesim Kırık Temizleme"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(630),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(632),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(631),
                            Name = "Örgü"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(634),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(636),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(635),
                            Name = "Saç Düzleştirme (Brezilya Fönü)"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(638),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(640),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(639),
                            Name = "Boya(Dip)"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(642),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(644),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(643),
                            Name = "Boya(Tüm Saç)"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(646),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(648),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(647),
                            Name = "Renk Değişimi"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(650),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(652),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(651),
                            Name = "Röfle"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(655),
                            DeletedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(656),
                            Description = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec qu",
                            IsDeleted = false,
                            ModifiedOn = new DateTime(2022, 11, 23, 21, 46, 22, 281, DateTimeKind.Local).AddTicks(655),
                            Name = "Dip Açma"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationUserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasDiscriminator().HasValue("ApplicationUserRole");

                    b.HasData(
                        new
                        {
                            UserId = "e26796d3-0f85-48fe-a864-4f523107c3bb",
                            RoleId = "35ca7aad-d2b3-49f4-ad0c-1fdbc2ed7ed8"
                        },
                        new
                        {
                            UserId = "b4a23211-6cba-4cd1-9e27-0b50aa6294d9",
                            RoleId = "ab2e09bf-cc27-43b5-bed9-1cc81c957abb"
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Appointment", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Salon", "Salon")
                        .WithMany("Appointments")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.ApplicationUser", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.SalonService", "SalonService")
                        .WithMany("Appointments")
                        .HasForeignKey("SalonId", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("SalonService");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Salon", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Category", "Category")
                        .WithMany("Salons")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.City", "City")
                        .WithMany("Salons")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.ApplicationUser", "Owner")
                        .WithMany("Salons")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SalonService", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Salon", "Salon")
                        .WithMany("Services")
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.Service", "Service")
                        .WithMany("Salons")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Salon");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Service", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.Category", "Category")
                        .WithMany("Services")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DataAccessLayer.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Roles");

                    b.Navigation("Salons");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Category", b =>
                {
                    b.Navigation("Salons");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.City", b =>
                {
                    b.Navigation("Salons");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Salon", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.SalonService", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DataAccessLayer.Entities.Service", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Salons");
                });
#pragma warning restore 612, 618
        }
    }
}
